### PR TITLE
Callback even if there is an error

### PR DESCRIPTION
**Pull request by CleristonBernardes**
I have been trying to use Mockgoose with parallel test execution and the "prepareStorage" method was not responding in case of error. It turned out that even with the internal error my tests would run successfully.

### CODE REVIEW

**Comment by CleristonBernardes** [comment]
Tests ran ok locally.

screen shot 2017-07-14 at 14 43 17

**Comment by winfinit** [comment]
@CleristonBernardes thank you for your PR, I am a bit confused about resolving an error vs throwing an error, is error not being caught somewhere, or it is not being propagated correctly upstream?

**Comment by CleristonBernardes** [comment]
The error is being caugth, but not sent back. Hence when invoking the method and there's an error no response is sent.

**Comment by yxliang01** [comment]
Hello @winfinit ,
Would you like to publish HEAD to npm (version: 7.3.4) ASAP? Because my CI stuff needs this correction. By the way, `mockgoose` is fantastic!

Thanks!

**Comment by CleristonBernardes** [comment]
Hey @yxliang01 you can use  my commit version while the version is not updated

"mockgoose": "git://github.com/CleristonBernardes/Mockgoose.git#e14ca7fa708d3f02bbace1b502036b62c75c271a"

Cheers

**Pull request merged**
