### PR TITLE
Upgrade packages to fix security vulnerability

### PR DESCRIPTION
**Pull request by gwilakers**
The debug@2.2.0 has a dependency on ms@0.7.1, which contains a security vulnerability by way of ReDos. More information on that can be found here: https://snyk.io/vuln/npm:ms:20170412.

All tests seem to be passing. Let me know if there is anything else needed before this can be merged in.

### CODE REVIEW

**Comment by gwilakers** [comment]
@winfinit Passed all the mocha tests on my local machine but noticed the build was failing prior to my pull request. Is there a problem with the upgraded packages I am trying to get merged in or is there something else causing the build to fail? Thanks.

**Comment by keymandll** [comment]
Would be nice to see this fixed.

**Comment by bompi88** [comment]
@mccormicka @winfinit any update on why this PR is not merged yet, please?

**Comment by LoneRifle** [comment]
Duplicate of #79

**Pull request closed without merging**
