### PR TITLE
Unmock promise support

### PR DESCRIPTION
**Pull request by markfejes**
Hey!

I've created this change list because this little modification helps my testing, and makes the code more readable. As I removed the callback from the unmock method this could be a major semver increase since it has no backwards compatibility. 

It would be very good if you could integrate it to the master branch @winfinit :)

Thank you!

### CODE REVIEW

**Comment by sgnl** [comment]
IMO, Should handle both callbacks and promises

**Comment by lino-silva** [comment]
Agreed - adding support for Promises shouldn't remove support for callbacks. Both are supported in mongoose, so it wouldn't make sense to drop it.

**Comment by winfinit** [comment]
I would like to stick with one interface, which is Promises. please submit this request again if you are interested for version 7.x

**Comment by winfinit** [comment]
I would like to stick with one interface, which is Promises. please submit this request again if you are interested for version 7.x

**Comment by markfejes** [comment]
I will not be able to work in this until the 25th of March unfortunately...

**Comment by markfejes** [comment]
I think this is not relevant to the new version! :)

**Pull request closed without merging**
